"""
run_queries.py
----------------
Executes every query in sql/queries.sql against risk_analysis.db and saves
the real results to results.md, so nothing in this project is a fabricated
example — every number comes from an actual query run.
"""
import re
import sqlite3
import pandas as pd

DB_PATH = "risk_analysis.db"
SQL_PATH = "sql/queries.sql"
OUTPUT_PATH = "results.md"


def split_queries(sql_text):
    """Split the .sql file into (title, query) pairs based on '-- Q<n>.' markers."""
    blocks = re.split(r"(?=-- Q\d+\.)", sql_text)
    queries = []
    for block in blocks:
        block = block.strip()
        if not block.startswith("-- Q"):
            continue
        title_match = re.match(r"-- (Q\d+\.[^\n]*)", block)
        title = title_match.group(1) if title_match else "Untitled"
        # Strip leading comment lines, keep the SQL statement itself
        lines = [l for l in block.split("\n")]
        sql_lines = [l for l in lines if not l.strip().startswith("--")]
        query = "\n".join(sql_lines).strip()
        if query:
            queries.append((title, query))
    return queries


def main():
    conn = sqlite3.connect(DB_PATH)
    with open(SQL_PATH) as f:
        sql_text = f.read()

    queries = split_queries(sql_text)
    print(f"Found {len(queries)} queries to run.\n")

    md_sections = ["# Query Results\n\nGenerated by running `run_queries.py` against `risk_analysis.db`.\n"]

    for title, query in queries:
        print(f"Running {title} ...")
        try:
            df = pd.read_sql_query(query, conn)
            md_sections.append(f"## {title}\n\n{df.to_markdown(index=False)}\n")
            print(df.head(8).to_string(index=False))
            print()
        except Exception as e:
            print(f"  FAILED: {e}\n")
            md_sections.append(f"## {title}\n\n_Query failed: {e}_\n")

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(md_sections))

    conn.close()
    print(f"\nAll results written to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
